const sections = [
  { id:"nos", title:"NOSE SECTION", items:[
    {id:"n1",  t:"Windshield/Side Windows – Clean and General Cond."},
    {id:"n2",  t:"Radome – Damage and Condition"},
    {id:"n3",  t:"Nose Gear Assembly – General Condition"},
    {id:"n4",  t:"Nose Gear Strut – Normal Extension"},
    {id:"n5",  t:"WOW Switch/Harness – Condition & Security"},
    {id:"n6",  t:"Nose Gear Axle Nut Retainers – Security"},
    {id:"n7",  t:"Nose Landing Gear Doors and Bay – Condition, Leaks and Locked"},
    {id:"n8",  t:"Nose Tires – Pressure & Condition (155 – 160)"},
    {id:"n9",  t:"Strut – Wipe Down/Clean (5606 Fluid)"},
    {id:"n10", t:"Brake Accumulator Pre-Load – 750 ± 50 psi"},
    {id:"n11", t:"Landing Gear Doors & Rods – Condition & Security"},
    {id:"n12", t:"Oxygen Systems – Per Placard"},
    {id:"n13", t:"Oxygen Vent – Clear"},
    {id:"n14", t:"General Area – Cleanliness, Condition & Leaks"},
  ]},
  { id:"fus", title:"FUSELAGE", items:[
    {id:"fu1",  t:"Main Door Seal – Damage and Condition"},
    {id:"fu2",  t:"Static Ports – Damage and Obstructions"},
    {id:"fu3",  t:"AOA Vanes – Damage and Condition"},
    {id:"fu4",  t:"Oxygen Blow-out Disks – Condition & Security"},
    {id:"fu5",  t:"ADG Bay Door – Closed, Condition"},
    {id:"fu6",  t:"Pitot Heat/TAT Probe – Condition & Obstruction"},
    {id:"fu7",  t:"Fuselage Exterior – Damage, Open Access Panels, and Fluid Leaks"},
    {id:"fu8",  t:"Antennas – Security"},
    {id:"fu9",  t:"APU Inlet and Exhaust – Condition & Obstruction"},
    {id:"fu10", t:"Pressurization Static Port Damage and Obstruction"},
    {id:"fu11", t:"General Area – Cleanliness, Condition & Leaks"},
  ]},
  { id:"wings", title:"WINGS – LEFT/RIGHT", lr:true, items:[
    {id:"w1",  t:"Flaps – Damage and Condition Inboard Flap Slat"},
    {id:"w2",  t:"Leading Edge Anti-Ice Exhaust - Obstruction"},
    {id:"w3",  t:"Rear Beams – Condition & Cleanliness"},
    {id:"w4",  t:"Gravity Fuel Tank Filler Caps – Secured"},
    {id:"w5",  t:"Drain Water Condensate"},
    {id:"w6",  t:"Upper/Lower Surfaces Condition & Fuel Leaks"},
    {id:"w7",  t:"Static Dischargers – Damage and Condition"},
    {id:"w8",  t:"Aileron – Damage and Condition"},
    {id:"w9",  t:"Spoilers – Damage and Condition"},
    {id:"w10", t:"Landing Lights/Lenses – Condition"},
    {id:"w11", t:"Winglets – Damage and Condition"},
    {id:"w12", t:"General Area – Cleanliness, Security & Leaks"},
  ]},
  { id:"mlg_wells", title:"MAIN WHEEL WELLS - LEFT/RIGHT", lr:true, items:[
    {id:"mw1", t:"Main Gear Assemblies – General Condition"},
    {id:"mw2", t:"Main Gear Struts – Normal Extension"},
    {id:"mw3", t:"Struts – Wipe Down/Clean (5606 Fluid)"},
    {id:"mw4", t:"Tires – Pressure & Condition (185 - 193)"},
    {id:"mw5", t:"Brakes – Wear, Leaks, and Overheating"},
    {id:"mw6", t:"WOW Switch/Harness Condition & Security"},
    {id:"mw7", t:"# 3 Hydraulic Accumulator Pressure 1500 ±50 PSI"},
    {id:"mw8", t:"# 3 Hydraulic Filter Differential Pop-Up Buttons"},
    {id:"mw9", t:"General Area – Cleanliness, Condition & Leaks"},
  ]},
  { id:"tail_ext", title:"TAIL SECTION EXTERIOR", items:[
    {id:"te1", t:"Static Dischargers – Damage"},
    {id:"te2", t:"Access Doors/Panels – Security"},
    {id:"te3", t:"Antennas – Damage and Condition"},
    {id:"te4", t:"Stabilizers – Damage and Condition"},
    {id:"te5", t:"Elevators – Damage and Condition"},
    {id:"te6", t:"Rudder - Damage and Condition"},
    {id:"te7", t:"ACU Exhaust – Condition and Obstructions"},
    {id:"te8", t:"General Area – Cleanliness, Security & Leaks"},
  ]},
  { id:"tail_int", title:"TAIL SECTION INTERIOR", items:[
    {id:"ti1",  t:"APU Oil Level – Serviced Full"},
    {id:"ti2",  t:"APU Fire Bottle – 600 PSI at 70F"},
    {id:"ti3",  t:"Check Generator Adaptor Oil Level"},
    {id:"ti4",  t:"Check Pressure on # 1 Firex Container 600 PSI at 70F"},
    {id:"ti5",  t:"Check Pressure on # 2 Firex Container 600 PSI at 70F"},
    {id:"ti6",  t:"Check Pressure on APU Firex Container 600 PSI at 70F"},
    {id:"ti7",  t:"# 1 Hydraulic Accumulator Pressure 1500 ±50 PSI"},
    {id:"ti8",  t:"# 2 Hydraulic Accumulator Pressure 1500 ±50 PSI"},
    {id:"ti9",  t:"# 1 Hydraulic Filter Differential Pop-Up Buttons"},
    {id:"ti10", t:"# 2 Hydraulic Filter Differential Pop-Up Buttons"},
    {id:"ti11", t:"Engine Oil Servicing Reservoir – Full"},
    {id:"ti12", t:"Hydraulic Fluid Servicing Reservoir – Full (Skydrol)"},
    {id:"ti13", t:"General Area – Cleanliness, Security & Leaks"},
  ]},
  { id:"engines", title:"ENGINES – PYLONS – LEFT/RIGHT", lr:true, items:[
    {id:"en1", t:"Intakes/Fan Rotor – Condition & FOD"},
    {id:"en2", t:"Cowling Latches – Security"},
    {id:"en3", t:"Cowling Inlets/Outlets – Obstructions & Leaks"},
    {id:"en4", t:"Exhaust/Turbine Area – Condition & FOD"},
    {id:"en5", t:"Access Panels/Doors – Security"},
    {id:"en6", t:"Engine Oil Levels"},
    {id:"en7", t:"Oil Filters – DPI Buttons & Leaks"},
    {id:"en8", t:"IDG – Oil level"},
    {id:"en9", t:"Visual Check Overboard for Leaks"},
    {id:"en10",t:"General Area – Cleanliness, Security & Leaks"},
    {id:"en11",t:"Engine Cowl Anti Ice Pressure Relief Valve"},
  ]},
  { id:"lights", title:"LIGHTS", items:[
    {id:"l1",  t:"All Exterior Lights – Checked"},
    {id:"l2",  t:"Main/Nose Gear Utility Lights – Checked"},
    {id:"l3",  t:"Cockpit Instrument / Warning Lights – Checked"},
    {id:"l4",  t:"Passenger Warning Lights – Checked"},
    {id:"l5",  t:"Vestibule/Air Stair Lights – Checked"},
    {id:"l6",  t:"Forward Lav Lights – Checked"},
    {id:"l7",  t:"Forward/Aft Cabin Lighting – Checked"},
    {id:"l8",  t:"Galley Lights – Checked"},
    {id:"l9",  t:"Aft Lav Lights – Checked"},
    {id:"l10", t:"Baggage Compartment/Loading Lights – Checked"},
    {id:"l11", t:"Aft Equipment Bay Inspection Light - Checked"},
  ]},
  { id:"cockpit", title:"COCKPIT/CABIN AREAS", items:[
    {id:"cc1",  t:"Flashlights – Checked"},
    {id:"cc2",  t:"Cockpit Windshields – Clean"},
    {id:"cc3",  t:"Maintenance Forms – Reviewed"},
    {id:"cc4",  t:"Emergency Exit – Condition & Security"},
    {id:"cc5",  t:"First Aid Kit – Condition & Accessibility"},
    {id:"cc6",  t:"Baggage Door Seal – Condition & Security"},
    {id:"cc7",  t:"Rafts / Vest check due date"},
    {id:"cc8",  t:"Loose Equipment – Stowed"},
    {id:"cc9",  t:"Overwing Exit – Closed and Secure"},
    {id:"cc10", t:"Portable Fire Extinguisher – Pressure and Tamper Indicator not Broken"},
    {id:"cc11", t:"General Area – Cleanliness, Security & Leaks"},
  ]},
  { id:"final", title:"FINAL CHECK", items:[
    {id:"fc1", t:"Cleaning – Complete"},
    {id:"fc2", t:"Lav – Dumped & Re-Serviced"},
    {id:"fc3", t:"Potable Water – Serviced Full"},
    {id:"fc4", t:"Power/Batteries – Off"},
    {id:"fc5", t:"All Doors – Closed (Lock as Required)"},
    {id:"fc6", t:"Wheel Chocks – Installed"},
  ]},
];

export default {
  id: "challenger604",
  name: "Challenger 604",
  shortName: "CL604",
  title: "ADVANCED AIR, LLC",
  subtitle: "CHALLENGER 604 MAINTENANCE PREFLIGHT CHECK",
  tailPresets: [],
  headerFields: [
    { id:"name", label:"Name",            wizardCollected:true  },
    { id:"date", label:"Date",            wizardCollected:true  },
    { id:"cert", label:"Cert. #",         wizardCollected:true,  mono:true },
    { id:"tail", label:"Aircraft Tail #", wizardCollected:true,  mono:true, prominent:true, prefix:"N" },
    { id:"sn",        label:"S/N",        wizardCollected:false, mono:true, secondary:true },
    { id:"totalTime", label:"Total Time", wizardCollected:false, mono:true, secondary:true },
    { id:"cyc",       label:"CYC",        wizardCollected:false, mono:true, secondary:true },
    { id:"apuTt",     label:"APU TT",     wizardCollected:false, mono:true, secondary:true },
  ],
  sections,
  layout: {
    left:  ["nos","fus","wings","mlg_wells","lights","cockpit","final"],
    right: ["engines","tail_ext","tail_int"],
  },
  serviceBlock: {
    questions: [
      { id:"tires", label:"Were tires serviced?",  footerLabel:"Serviced Tires"  },
      { id:"oxy",   label:"Was oxygen serviced?", footerLabel:"Serviced Oxygen" },
      { id:"oil",   label:"Was oil serviced?",    footerLabel:"Serviced Oil"    },
      { id:"idg",   label:"Was IDG serviced?",    footerLabel:"Serviced IDG"    },
    ],
    oil: {
      options: ["BP 2380","MOBIL 254","Aeroshell 500"],
      default: null,
      qtyLabel: "Qty",
    },
  },
  warning: null,
};
