const sections = [
  { id:"nos", title:"NOSE SECTION", items:[
    {id:"n1",  t:"Pitot Heat/TAT Probe – Condition & Obstruction"},
    {id:"n2",  t:"Windshield Wipers – Condition & Security"},
    {id:"n3",  t:"Windshield/Side Windows – Clean & General Cond."},
    {id:"n4",  t:"Radoms – Condition & Security"},
    {id:"n5",  t:"Nose Gear Assembly – General Condition"},
    {id:"n6",  t:"Nose Gear Strut – Normal Extension"},
    {id:"n7",  t:"Power Steering Pin – Security"},
    {id:"n8",  t:"Nutcracker Switch/Harness – Condition & Security"},
    {id:"n9",  t:"Nose Gear Axle Nut Retainers – Security"},
    {id:"n10", t:"L/H Tire – Pressure & Condition (115 ± 5psi)"},
    {id:"n11", t:"R/H Tire – Pressure & Condition (115 ± 5psi)"},
    {id:"n12", t:"Strut – Wipe Down/Clean (5606 Fluid)"},
    {id:"n13", t:"Landing Gear Dump Bottle – 3000 PSI at 70F"},
    {id:"n14", t:"Brake Accumulator Pre-Load – 1200 PSI at 70F"},
    {id:"n15", t:"Landing Gear Doors & Rods – Condition & Security"},
    {id:"n16", t:"Nose Gear Uplock – Open/Cam Roller Freedom"},
    {id:"n17", t:"Taxi Lights – Condition & Security"},
    {id:"n18", t:"Oxygen Systems – 1600 to 1800 PSI"},
    {id:"n19", t:"Oxygen Vent – Clear"},
    {id:"n20", t:"General Area – Cleanliness, Condition & Leaks"},
  ]},
  { id:"lff", title:"LEFT FORWARD FUSELAGE", items:[
    {id:"lf1",  t:"Wheel Well Doors – Open"},
    {id:"lf2",  t:"Angle of Attack (AOA) vane – Cover Removed/check"},
    {id:"lf3",  t:"L/R Total Air Temperature (TAT) probes – Cover Removed/Check"},
    {id:"lf4",  t:"Ice detection probe – Check"},
    {id:"lf5",  t:"Pitot probes – Covers removed/check"},
    {id:"lf6",  t:"Forward external switch panel door - Switches OFF/Door Secure"},
    {id:"lf7",  t:"Radome – Check"},
    {id:"lf8",  t:"Windshield - Check"},
    {id:"lf9",  t:"Nose Landing Gear (NLG) wheel well area – Check"},
    {id:"lf10", t:"NGL uplock – Open"},
    {id:"lf11", t:"Parking brake accumulator – Check (3000 psi)"},
    {id:"lf12", t:"Emergency landing gear extension bottle – Check (3100 psi)"},
    {id:"lf13", t:"NLG safety pin – Remove"},
    {id:"lf14", t:"NLG door control valve – Pin removed/Flight position/cover secure"},
    {id:"lf15", t:"NLG fairing door/electrical wires/strut – Check"},
    {id:"lf16", t:"Nose Wheel Steering (NWS) unit overtravel indicator – Check (If popped, maintenance action is required.)"},
    {id:"lf17", t:"Taxi lights/NLG tires – Check"},
    {id:"lf18", t:"NLG torque link – Pinned/Safetied"},
    {id:"lf19", t:"NLG WOW switch - Check"},
  ]},
  { id:"rfw", title:"RIGHT FUSELAGE AND WING", lr:true, items:[
    {id:"rf1",  t:"Ice detection probe – Check"},
    {id:"rf2",  t:"Pitot probes – Cover Removed/check"},
    {id:"rf3",  t:"TAT probe – Covers Removed/check"},
    {id:"rf4",  t:"AOA vane – Covers Removed/check"},
    {id:"rf5",  t:"Pressure relief valve/outflow valves – Clear"},
    {id:"rf6",  t:"External dc power door – Check/secure"},
    {id:"rf7",  t:"External ac power door – Check/secure"},
    {id:"rf8",  t:"PRV static ports – Cover removed/checked"},
    {id:"rf9",  t:"Oxygen system overboard discharge disk – Intact"},
    {id:"rf10", t:"Oxygen quantity – Checked (1800 psi, 1500 psi minimum)"},
    {id:"rf11", t:"Oxygen service door – Secure"},
    {id:"rf12", t:"Antennas – Check"},
    {id:"rf13", t:"Right Ice Inspection/Emergency Lights - Check"},
    {id:"rf14", t:"Window Emergency releases/windows – Secure"},
    {id:"rf15", t:"Right landing light - Check"},
    {id:"rf16", t:"Wing vent – Clear"},
    {id:"rf17", t:"Engine inlet/cooling inlets – Cover removed/Check"},
    {id:"rf18", t:"Fuel servicing panel and door – Check/door secure"},
    {id:"rf19", t:"Fuel sump drains – Check/not leaking fuel"},
    {id:"rf20", t:"Beacon – Check"},
    {id:"rf21", t:"Pressure fueling static port – Clear"},
    {id:"rf22", t:"Wing leading edge - Check"},
    {id:"rf23", t:"Fuel tank vent and VGs(installed by ASC 159) – Check"},
    {id:"rf24", t:"Fuel Tank plenum drain – Check"},
    {id:"rf25", t:"NAV/Strobe light/wing tip- Check"},
    {id:"rf26", t:"Winglet – Check"},
    {id:"rf27", t:"Static Wicks (3) – Check"},
    {id:"rf28", t:"Aileron/aileron bungee/flaps/spoilers – Check"},
    {id:"rf29", t:"MLG fairing door/strut – Check"},
    {id:"rf30", t:"MLG Brake wear indicators (inboard/outboard) - Check"},
    {id:"rf31", t:"MLG Tire/brakes (tire pressure 190 psi) - Check"},
    {id:"rf32", t:"MLG wheel flange retaining rings (inboard/outboard) – Check"},
    {id:"rf33", t:"MLG WOW switch – Check"},
    {id:"rf34", t:"Flap drive rods – Check"},
    {id:"rf35", t:"MLG uplock – Open"},
    {id:"rf36", t:"MLG wheel well area – Check"},
    {id:"rf37", t:"Main fuel shut-off valve position – Verify Open"},
    {id:"rf38", t:"Fuel boost pumps – Check/no leaks"},
    {id:"rf39", t:"Right MLG door control valve – Pin removed/Flight position"},
    {id:"rf40", t:"MLG safety pin - Remove"},
    {id:"rf41", t:"Aft Lavatory service door – Secure"},
    {id:"rf42", t:"Wing anti-icing vents – Clear"},
    {id:"rf43", t:"Aft Fuselage antennas – Check"},
    {id:"rf44", t:"Engine Cowl/accessory door/vents/exhaust – Check/secure/clear"},
    {id:"rf45", t:"Auxiliary Power Unit (APU) exhaust - Clear"},
  ]},
  { id:"lfw", title:"LEFT FUSELAGE AND WING", lr:true, items:[
    {id:"lw1",  t:"Baggage door – Secure"},
    {id:"lw2",  t:"MLG wheel well area – Check"},
    {id:"lw3",  t:"Main fuel shut-off valve position – verify OPEN"},
    {id:"lw4",  t:"Fuel Boost pumps – Check/no leaks"},
    {id:"lw5",  t:"Cockpit/Cabin trim air valve vent elbow – Check/clear"},
    {id:"lw6",  t:"Flap drive rods – Check"},
    {id:"lw7",  t:"MLG uplock – Open"},
    {id:"lw8",  t:"MLG side brace actuator and sequencing linkage – Check"},
    {id:"lw9",  t:"MLG fairing door/strut – Check"},
    {id:"lw10", t:"MLG WOW switch – Check"},
    {id:"lw11", t:"MGL wheel flange retaining rings (inboard/outboard) - Check"},
    {id:"lw12", t:"MLG tires/brakes – Check"},
    {id:"lw13", t:"MLG brake wear indicators (inboard/outboard) – Check"},
    {id:"lw14", t:"MLG door control valve – Pin removed/FLIGHT position"},
    {id:"lw15", t:"MLG safety pin – Remove"},
    {id:"lw16", t:"Flaps/spoilers/aileron/aileron bungee – Check"},
    {id:"lw17", t:"Static wicks (3) – Check"},
    {id:"lw18", t:"Winglet – Check"},
    {id:"lw19", t:"NAV/Strobe light/wing tip – Check"},
    {id:"lw20", t:"Fuel tank plenum drain - Check"},
    {id:"lw21", t:"Fuel tank vent and VGs (installed by ASC 159) – Check"},
    {id:"lw22", t:"Wing leading edge – Check"},
    {id:"lw23", t:"Pressure fueling static port - Clear"},
    {id:"lw24", t:"Fuel sump drains – Check"},
    {id:"lw25", t:"Engine Inlet/cooling inlets – cover removed/check"},
    {id:"lw26", t:"Window emergency releases/windows – Secure"},
    {id:"lw27", t:"Emergency lights/ice inspection lights – Check"},
    {id:"lw28", t:"Landing light – Check"},
    {id:"lw29", t:"Wing Vent – Clear"},
    {id:"lw30", t:"Main Entrance door/seal - Check"},
    {id:"lw31", t:"Door control valve pins/landing gear safety pins/pitot probe Covers - Stowed"},
  ]},
  { id:"laf", title:"LEFT AFT FUSELAGE", items:[
    {id:"la1", t:"Heat Exchanger exhaust – Clear"},
    {id:"la2", t:"Precooler exhaust – Clear"},
    {id:"la3", t:"Engine cowl/accessory door/vents/exhaust – Check/Secure/clear"},
  ]},
  { id:"tcomp", title:"TAIL COMPARTMENT", items:[
    {id:"tc1",  t:"GND PWR RCPT Circuit Breaker (CB) – Check"},
    {id:"tc2",  t:"GND SVR BUS switch – ON"},
    {id:"tc3",  t:"GND SVR BUS indicator – Check"},
    {id:"tc4",  t:"Utility Lights Switch – ON"},
    {id:"tc5",  t:"Right Battery Charger – Check"},
    {id:"tc6",  t:"Hydraulic replenisher fluid level/manual selector valve/Pump switch/Check fluid level/valve OFF/switch OFF"},
    {id:"tc7",  t:"Right Hydraulic system filter DPIs (3) – Check"},
    {id:"tc8",  t:"Main Batteries (left and right) – Check"},
    {id:"tc9",  t:"Power Transfer Unit (PTU) DPI (1) – Check"},
    {id:"tc10", t:"Right Hydraulic system reservoir quantity - Check"},
    {id:"tc11", t:"APU tailpipe – Check"},
    {id:"tc12", t:"AUX power relay box CBs (6) – Check"},
    {id:"tc13", t:"Left Hydraulic system reservoir quantity – Check"},
    {id:"tc14", t:"BLEED AIR isolation valve – Check"},
    {id:"tc15", t:"Ozone filters (left and right) - Check"},
    {id:"tc16", t:"Air Conditioning packs (left and right) – Check"},
    {id:"tc17", t:"Left Hydraulic system filter DPIs (5) – Check"},
    {id:"tc18", t:"Left Battery Charger – Check"},
    {id:"tc19", t:"L/R hydraulic accumulators – Check (1200 psi)"},
    {id:"tc20", t:"Engine oil level – SERVICE IAW FLT MANUAL SUPP"},
    {id:"tc21", t:"Elevator Actuators (2) – Check"},
    {id:"tc22", t:"Rudder Actuator - Check"},
    {id:"tc23", t:"UTILITY LIGHTS switch –OFF"},
    {id:"tc24", t:"GND SVR BUS switch - OFF"},
  ]},
  { id:"interior", title:"INTERIOR", items:[
    {id:"in1", t:"Baggage compartment door – Check/secure"},
    {id:"in2", t:"AUX pressure bulkhead door – Check/secure"},
    {id:"in3", t:"Baggage door seal control valve selector – NORMAL OPS"},
    {id:"in4", t:"Windows – Secure"},
    {id:"in5", t:"Fuel Tank Caps – Secure"},
    {id:"in6", t:"Wing Vortex generators – Check"},
    {id:"in7", t:"Cabin Area – Secure"},
    {id:"in8", t:"System monitor/test panel - Check"},
  ]},
  { id:"tail_ext", title:"TAIL SECTION EXTERIOR", items:[
    {id:"te1", t:"Static Dischargers(7) – Condition & Security"},
    {id:"te2", t:"Access Doors/Panels – Security"},
    {id:"te3", t:"Antennas – Condition & Security"},
    {id:"te4", t:"Flap/Stabilizer – Check Relative Positions"},
    {id:"te5", t:"Elevator/ Trim Tabs – Condition & Security"},
    {id:"te6", t:"Rudder- Condition & Security"},
    {id:"te7", t:"Tail cone navigation light/static wick (2)"},
    {id:"te8", t:"General Area – Cleanliness, Security & Leaks"},
  ]},
  { id:"cockpit", title:"COCKPIT/CABIN AREAS", items:[
    {id:"cc1",  t:"Circuit Breakers checked/ EER's, PDB's, Cockpit overhead panels"},
    {id:"cc2",  t:"Emergency Power - Checked"},
    {id:"cc3",  t:"Left/ right batteries - ON (22-27Vdc)"},
    {id:"cc4",  t:"Emergency Power – OFF - Select"},
    {id:"cc5",  t:"Cabin Pressure Control - Check outflow valve open"},
    {id:"cc6",  t:"Parking brake accumulator pressure - Check. Note: Accumulator precharge pressure (1200 psi)"},
    {id:"cc7",  t:"Flaps - Set (10° recommended for preflight)"},
    {id:"cc8",  t:"Parking Brake - Set"},
    {id:"cc9",  t:"BRAKE PRESS indicator - Check (3000 psi)"},
    {id:"cc10", t:"Fuel Quantity - Check"},
    {id:"cc11", t:"Oxygen Quantity - Check (1800 psi minimum)"},
    {id:"cc12", t:"Left/Right Batteries - OFF"},
  ]},
  { id:"tail_int", title:"TAIL SECTION INTERIOR", items:[
    {id:"ti1",  t:"APU Oil Level – Serviced Full (Exxon 2380)"},
    {id:"ti2",  t:"APU Fire Bottle – 600 PSI at 70F"},
    {id:"ti3",  t:"Combined Sys. Quantity Gauge – Full (Gear Doors Closed)"},
    {id:"ti4",  t:"Flight Sys. Quantity Gauge – Full (Gear Doors Closed)"},
    {id:"ti5",  t:"Comb./Flt. Filters – DPI Buttons, Condition & Leaks"},
    {id:"ti6",  t:"Control Cables/Actuators – Condition & Security"},
    {id:"ti7",  t:"Stab Drive Rods/Swell Rods – Security & Alignment"},
    {id:"ti8",  t:"Aux Power Relay Box – C/Bs In"},
    {id:"ti9",  t:"Engine/APU Fire Bottle Cartridges – Wires Connected"},
    {id:"ti10", t:"APU Inlet Screen – Obstructions & Condition"},
    {id:"ti11", t:"Heat Exchangers – Obstructions & Condition"},
    {id:"ti12", t:"T/R Control Valve Pins – Stowed"},
    {id:"ti13", t:"Engine Oil Servicing Reservoir - Full"},
    {id:"ti14", t:"Hydraulic Fluid Servicing Reservoir – Full (Skydrol)"},
    {id:"ti15", t:"General Area – Cleanliness, Security & Leaks"},
  ]},
  { id:"lights", title:"LIGHTS", items:[
    {id:"l1",  t:"All Exterior Lights – Checked"},
    {id:"l2",  t:"Main/Nose Gear Utility Lights – Checked"},
    {id:"l3",  t:"Cockpit Instrument / Warning Lights – Checked"},
    {id:"l4",  t:"Passenger Warning Lights – Checked"},
    {id:"l5",  t:"Vestibule/Air Stair Lights – Checked"},
    {id:"l6",  t:"Forward Lav Lights – Checked"},
    {id:"l7",  t:"Forward/Aft Cabin Lighting – Checked"},
    {id:"l8",  t:"Galley Lights – Checked"},
    {id:"l9",  t:"Aft Lav Lights – Checked"},
    {id:"l10", t:"Baggage Compartment/Loading Lights – Checked"},
    {id:"l11", t:"Aft Equipment Bay Inspection Light - Checked"},
  ]},
  { id:"final", title:"FINAL CHECK", items:[
    {id:"fc1", t:"Cleaning – Complete"},
    {id:"fc2", t:"Lav – Dumped & Reserviced"},
    {id:"fc3", t:"Potable Water – Serviced Full"},
    {id:"fc4", t:"Power/Batteries – Off"},
    {id:"fc5", t:"Gust Lock – Engaged"},
    {id:"fc6", t:"All Doors – Closed (Lock as Required)"},
    {id:"fc7", t:"Wheel Chocks – Installed"},
    {id:"fc8", t:"Engine Covers – Installed"},
    {id:"fc9", t:"Out Flow Valve Cover – Installed"},
  ]},
];

export default {
  id: "g450",
  name: "Gulfstream G450",
  shortName: "G450",
  title: "ADVANCED AIR, LLC",
  subtitle: "G450 MAINTENANCE PREFLIGHT CHECK",
  tailPresets: [],
  headerFields: [
    { id:"name", label:"Name",            wizardCollected:true  },
    { id:"date", label:"Date",            wizardCollected:true  },
    { id:"cert", label:"Cert. #",         wizardCollected:true,  mono:true },
    { id:"tail", label:"Aircraft Tail #", wizardCollected:true,  mono:true, prominent:true, prefix:"N" },
    { id:"totalTime", label:"A/C Total Time", wizardCollected:false, mono:true, secondary:true },
    { id:"tcyc",      label:"TCYC",           wizardCollected:false, mono:true, secondary:true },
    { id:"apuTime",   label:"APU Total Time", wizardCollected:false, mono:true, secondary:true },
    { id:"sn",        label:"S/N",            wizardCollected:false, mono:true, secondary:true },
  ],
  sections,
  layout: {
    left:  ["nos","lff","rfw","lfw","laf","tcomp"],
    right: ["interior","tail_ext","cockpit","tail_int","lights","final"],
  },
  serviceBlock: {
    questions: [
      { id:"tires", label:"Were tires serviced?",  footerLabel:"Serviced Tires"  },
      { id:"oxy",   label:"Was oxygen serviced?", footerLabel:"Serviced Oxygen" },
      { id:"oil",   label:"Was oil serviced?",    footerLabel:"Serviced Oil"    },
    ],
    oil: {
      options: null,
      default: null,
      qtyLabel: "Qty",
    },
  },
  warning: null,
};
