const sections = [
  { id:"docs", title:"DOCUMENTATION & RECORDS", items:[
    {id:"d1",  t:"Aircraft logbooks current and on board"},
    {id:"d2",  t:"Airworthiness certificate displayed"},
    {id:"d3",  t:"Registration certificate current and on board"},
    {id:"d4",  t:"Weight & balance data current and applicable for this flight"},
    {id:"d5",  t:"MEL/CDL reviewed — all deferred items placarded and logged"},
    {id:"d6",  t:"Maintenance release signed off by authorized inspector"},
    {id:"d7",  t:"Inspection status current (Phase / 100-hr / Annual as applicable)"},
    {id:"d8",  t:"AD compliance verified — no outstanding ADs"},
    {id:"d9",  t:"Engine time / cycles reviewed — within limits"},
    {id:"d10", t:"APU status reviewed — operational or MEL'd correctly"},
  ]},
  { id:"apu", title:"APU (IF EQUIPPED)", items:[
    {id:"a1", t:"APU access door / cowling secured and latched"},
    {id:"a2", t:"APU intake screen clear — no FOD, ice, or debris"},
    {id:"a3", t:"APU exhaust clear of obstructions and personnel"},
    {id:"a4", t:"APU oil level within limits (if dipstick accessible)"},
    {id:"a5", t:"APU fire bottle armed — pressure in green"},
    {id:"a6", t:"APU drain mast clear and unobstructed"},
    {id:"a7", t:"APU bleed / electrical selector verified per MEL if APU inop"},
  ]},
  { id:"engInlet", title:"ENGINE(S) — INLET & EXTERIOR", items:[
    {id:"ei1",  t:"Inlet cover(s) removed and stowed"},
    {id:"ei2",  t:"Inlet duct — no FOD, ice, standing water, or debris"},
    {id:"ei3",  t:"Fan blades — visually inspect all for nicks, dents, cracks, or FOD damage"},
    {id:"ei4",  t:"Fan blade leading edges serviceable (no sharp nicks per limits)"},
    {id:"ei5",  t:"Fan hub and spinner — no cracks, missing fasteners, or obvious damage"},
    {id:"ei6",  t:"Inlet cowl latches secure, all fasteners present"},
    {id:"ei7",  t:"Inlet lip — no dents, deformation, or de-icer damage"},
    {id:"ei8",  t:"Nose cowl anti-ice ports unobstructed"},
    {id:"ei9",  t:"Engine mount / pylon fairings — no cracks, missing panels"},
    {id:"ei10", t:"Thrust reverser doors — stowed, locked, no damage or gap"},
    {id:"ei11", t:"Reverser blocker doors / cascade vanes — no visible damage"},
    {id:"ei12", t:"Reverser actuator links visible check — no obvious looseness"},
    {id:"ei13", t:"Core exhaust — no cracks, missing tiles, or heat damage"},
    {id:"ei14", t:"Turbine exhaust nozzle — check for sooting, streaks, or burn-through"},
    {id:"ei15", t:"Tailpipe — no foreign object accumulation"},
    {id:"ei16", t:"Engine drain mast — unobstructed, no excessive streaking"},
    {id:"ei17", t:"Fuel / oil / hydraulic lines at engine — no seeping or chafing"},
    {id:"ei18", t:"Fire detection loop routing visible check — no obvious damage"},
    {id:"ei19", t:"Engine fire bottle pressure in green"},
  ]},
  { id:"engOil", title:"ENGINE OIL & FLUIDS", items:[
    {id:"eo1", t:"Engine oil quantity within operating range (per AMM servicing limits)"},
    {id:"eo2", t:"Oil filler cap secure and safety-wired"},
    {id:"eo3", t:"No oil leaks at accessory gearbox, seals, or case"},
    {id:"eo4", t:"Oil cooler and lines — no seeping or swelling"},
    {id:"eo5", t:"IDG / CSD oil level checked (if accessible ground-level)"},
    {id:"eo6", t:"Hydraulic reservoir quantity within limits — all systems"},
    {id:"eo7", t:"Hydraulic lines and fittings at engine pylon — no seeping"},
    {id:"eo8", t:"No fuel streaking or pooling beneath engine pylon"},
  ]},
  { id:"cockpit", title:"COCKPIT & FLIGHT DECK", items:[
    {id:"c1",  t:"All gust locks and control locks removed and stowed"},
    {id:"c2",  t:"Flight controls — free and correct throughout full travel"},
    {id:"c3",  t:"Trim — verified at takeoff setting"},
    {id:"c4",  t:"Seats, rudder pedals, and harnesses adjusted and secured"},
    {id:"c5",  t:"Emergency equipment on board (ELT, fire extinguisher, first aid, life vests if required)"},
    {id:"c6",  t:"ELT armed, battery in date, last inspection current"},
    {id:"c7",  t:"EFIS / avionics — powered on, no fault flags or amber alerts"},
    {id:"c8",  t:"Engine FADEC / EEC self-test — no fault codes"},
    {id:"c9",  t:"FMS / CDU — database current, route loaded and verified"},
    {id:"c10", t:"Anti-ice / de-ice systems — tested and operational"},
    {id:"c11", t:"Pitot heat — confirmed operational"},
    {id:"c12", t:"All circuit breakers in — none tripped"},
    {id:"c13", t:"Oxygen system pressure within limits, masks accessible"},
    {id:"c14", t:"Pressurization system — outflow valve position verified"},
    {id:"c15", t:"APU / GPU power — connected if required for cold soak start"},
    {id:"c16", t:"Fuel panel — quantity confirmed, cross-feed and transfer switches set"},
    {id:"c17", t:"Hydraulic panel — all systems show normal pressure / quantity"},
    {id:"c18", t:"Landing gear handle — down and locked indication confirmed"},
    {id:"c19", t:"Flap / slat control — set to takeoff position, indicator confirms"},
    {id:"c20", t:"Transponder — code set, Mode C/S active"},
    {id:"c21", t:"Master warning / caution — no illuminated lights after self-test"},
  ]},
  { id:"fuel", title:"FUEL SYSTEM", items:[
    {id:"f1", t:"Total fuel uplifted confirmed — matches dispatch release"},
    {id:"f2", t:"Fuel type confirmed — Jet-A / Jet-A1 as applicable"},
    {id:"f3", t:"Fuel density / specific gravity logged if required"},
    {id:"f4", t:"All fuel caps re-torqued and secured"},
    {id:"f5", t:"Fuel sumps drained — all clear, no water or contamination"},
    {id:"f6", t:"Overwing / pressure fueling ports capped and locked"},
    {id:"f7", t:"Fuel vent outlets unobstructed — no ice or debris"},
    {id:"f8", t:"No fuel staining or streaking on wing upper / lower skins"},
    {id:"f9", t:"Fuel jettison nozzles capped (if equipped)"},
    {id:"f10",t:"Cross-feed valves verified in correct position"},
  ]},
  { id:"leftWing", title:"LEFT WING", items:[
    {id:"lw1",  t:"Leading edge slat panels — no damage, gaps, or missing fasteners"},
    {id:"lw2",  t:"Slat tracks and carriages — no visible damage or binding"},
    {id:"lw3",  t:"Wing upper skin — no wrinkles, buckling, or impact damage"},
    {id:"lw4",  t:"Wing lower skin — no dents, corrosion, or fastener popping"},
    {id:"lw5",  t:"Aileron — full travel, no binding, gap seals intact"},
    {id:"lw6",  t:"Spoiler panels — stowed, no gaps, actuator rods visible check"},
    {id:"lw7",  t:"Outboard flap — stowed, no damage, all hinge points present"},
    {id:"lw8",  t:"Inboard flap — stowed, fairings secure"},
    {id:"lw9",  t:"Flap tracks and carriages — no FOD, lubrication adequate"},
    {id:"lw10", t:"Fuel cap(s) — secure and locked"},
    {id:"lw11", t:"Fuel vent outlet — clear"},
    {id:"lw12", t:"Wing tip — no damage, nav / strobe light lens intact"},
    {id:"lw13", t:"Winglet / sharklet — no delamination, cracks, or impact marks"},
    {id:"lw14", t:"Static wicks — all present and undamaged"},
    {id:"lw15", t:"Pitot / AOA / static ports — covers removed, unobstructed"},
    {id:"lw16", t:"TAT probe — undamaged, unobstructed"},
  ]},
  { id:"rightWing", title:"RIGHT WING", items:[
    {id:"rw1",  t:"Leading edge slat panels — no damage, gaps, or missing fasteners"},
    {id:"rw2",  t:"Slat tracks and carriages — no visible damage or binding"},
    {id:"rw3",  t:"Wing upper skin — no wrinkles, buckling, or impact damage"},
    {id:"rw4",  t:"Wing lower skin — no dents, corrosion, or fastener popping"},
    {id:"rw5",  t:"Aileron — full travel, no binding, gap seals intact"},
    {id:"rw6",  t:"Spoiler panels — stowed, no gaps, actuator rods visible check"},
    {id:"rw7",  t:"Outboard flap — stowed, no damage, all hinge points present"},
    {id:"rw8",  t:"Inboard flap — stowed, fairings secure"},
    {id:"rw9",  t:"Flap tracks and carriages — no FOD, lubrication adequate"},
    {id:"rw10", t:"Fuel cap(s) — secure and locked"},
    {id:"rw11", t:"Fuel vent outlet — clear"},
    {id:"rw12", t:"Wing tip — no damage, nav / strobe light lens intact"},
    {id:"rw13", t:"Winglet / sharklet — no delamination, cracks, or impact marks"},
    {id:"rw14", t:"Static wicks — all present and undamaged"},
  ]},
  { id:"fuse", title:"FUSELAGE & LANDING GEAR", items:[
    {id:"fg1",  t:"Nose radome — no delamination, cracks, or impact damage"},
    {id:"fg2",  t:"Nose radome latches — secure"},
    {id:"fg3",  t:"Forward fuselage skin — no dents, loose fasteners, or damage"},
    {id:"fg4",  t:"Cabin door seals — no visible damage or tears"},
    {id:"fg5",  t:"Cargo door seals and latches — secure"},
    {id:"fg6",  t:"Service panel doors — all closed and latched"},
    {id:"fg7",  t:"Belly fairing panels — all secured"},
    {id:"fg8",  t:"Fuselage antennas — secure, no missing fasteners"},
    {id:"fg9",  t:"Nose gear — tires inflated, no cuts, flat spots, or cord showing"},
    {id:"fg10", t:"Nose gear strut — extension within limits, no leaking"},
    {id:"fg11", t:"Nose gear doors — no damage, close properly"},
    {id:"fg12", t:"Nose gear steering linkage — visible check, no looseness"},
    {id:"fg13", t:"Nose gear torque links — no excessive play"},
    {id:"fg14", t:"Main gear — tires inflated, no cuts, flat spots, or cord showing"},
    {id:"fg15", t:"Main gear strut — extension within limits, no leaking"},
    {id:"fg16", t:"Main gear brake assemblies — pad thickness adequate, no glazing or heat cracking"},
    {id:"fg17", t:"Brake discs — no grooving beyond limits, no blue discoloration"},
    {id:"fg18", t:"Brake wear indicator pins — within serviceable limits"},
    {id:"fg19", t:"Main gear doors — no damage or cracks"},
    {id:"fg20", t:"Gear retraction mechanism — no hydraulic seeping at actuators"},
    {id:"fg21", t:"Ground spoiler / auto-brake system — armed per normal procedure"},
    {id:"fg22", t:"Gear down-lock indicators — confirmed (pins in / flags visible)"},
    {id:"fg23", t:"Landing / taxi lights — operational"},
    {id:"fg24", t:"All wheel well areas — clear of rags, tools, debris (FOD check)"},
  ]},
  { id:"emp", title:"EMPENNAGE (TAIL)", items:[
    {id:"em1",  t:"Horizontal stabilizer — no damage, dents, or loose skin panels"},
    {id:"em2",  t:"Elevator — full travel, no binding or excessive play"},
    {id:"em3",  t:"Elevator trim — set for takeoff, position matches cockpit indication"},
    {id:"em4",  t:"Elevator trim tab / actuator — secure, no freeplay"},
    {id:"em5",  t:"Vertical stabilizer — no cracks, loose fasteners, or impact marks"},
    {id:"em6",  t:"Rudder — full travel, no binding"},
    {id:"em7",  t:"Rudder trim / pedal limiter — per normal configuration"},
    {id:"em8",  t:"All hinge points — no excessive play or corrosion"},
    {id:"em9",  t:"Tail cone — secured, access panels latched"},
    {id:"em10", t:"APU exhaust area (if tail-mounted APU) — clear of heat damage"},
    {id:"em11", t:"Beacon light — operational"},
    {id:"em12", t:"Tail nav light — operational"},
    {id:"em13", t:"Static wicks — all present and undamaged"},
    {id:"em14", t:"Tail strike indicator — undamaged (if equipped)"},
  ]},
  { id:"final", title:"FINAL WALKAROUND", items:[
    {id:"fw1",  t:"All cowlings, access panels, and service doors latched and secured"},
    {id:"fw2",  t:"All pitot / static / TAT covers removed — accounted for"},
    {id:"fw3",  t:"All inlet and exhaust covers removed — accounted for"},
    {id:"fw4",  t:"GPU / ground power cable disconnected and stowed"},
    {id:"fw5",  t:"Ground hydraulic cart disconnected (if used)"},
    {id:"fw6",  t:"Fueling equipment clear of aircraft"},
    {id:"fw7",  t:"Wheel chocks removed — front and aft"},
    {id:"fw8",  t:"Tow bar removed and clear"},
    {id:"fw9",  t:"Tie-down chains / ropes removed"},
    {id:"fw10", t:"Full 360 FOD walk — ramp clear of debris"},
    {id:"fw11", t:"No fluid puddles beneath aircraft (fuel, oil, hydraulic)"},
    {id:"fw12", t:"Gear pins / safety locks removed and accounted for"},
    {id:"fw13", t:"Ground crew / personnel clear of engine inlet and exhaust arcs"},
    {id:"fw14", t:"Wing walker / ground crew briefed and in position"},
    {id:"fw15", t:"Crew notified — ready for APU / engine start"},
  ]},
];

export default {
  id: "universal",
  name: "Universal",
  shortName: "UNIV",
  title: "ADVANCED AIR, LLC",
  subtitle: "UNIVERSAL PREFLIGHT INSPECTION — Turbofan / Turbojet / Turboprop",
  tailPresets: [],
  headerFields: [
    { id:"name", label:"Name",            wizardCollected:true  },
    { id:"date", label:"Date",            wizardCollected:true  },
    { id:"cert", label:"Cert. #",         wizardCollected:true,  mono:true },
    { id:"tail", label:"Aircraft Tail #", wizardCollected:true,  mono:true, prominent:true, prefix:"N" },
  ],
  sections,
  layout: {
    left:  ["docs","apu","engInlet","engOil","cockpit","fuel"],
    right: ["leftWing","rightWing","fuse","emp","final"],
  },
  serviceBlock: {
    questions: [
      { id:"tires", label:"Were tires serviced?",  footerLabel:"Serviced Tires"  },
      { id:"oxy",   label:"Was oxygen serviced?", footerLabel:"Serviced Oxygen" },
      { id:"oil",   label:"Was oil serviced?",    footerLabel:"Serviced Oil"    },
    ],
    oil: {
      options: null,
      default: null,
      qtyLabel: "Qty",
    },
  },
  warning: "This checklist is for general mechanic reference only and is NOT a substitute for the applicable Aircraft Flight Manual (AFM), Airplane Maintenance Manual (AMM), or type-specific maintenance checklist. Always defer to manufacturer documentation and applicable FARs/regulations. Serviceable limits referenced herein must be verified against the applicable type's AMM.",
};
